const localQuotes = [
  "You're an awesome friend",
  "You're a gift to those around you",
  "You're a smart cookie",
  "You are awesome!",
  "You have impeccable manners",
  "I like your style",
  "You have the best laugh",
  "I appreciate you",
  "You are the most perfect you there is",
  "You are enough",
  "You're strong",
  "Your perspective is refreshing",
  "I'm grateful to know you",
  "You light up the room",
  "You deserve a hug right now",
  "You should be proud of yourself",
  "You're more helpful than you realize",
  "You have a great sense of humor",
  "You've got an awesome sense of humor!",
  "You are really courageous",
  "Your kindness is a balm to all who encounter it",
  "You're all that and a super-size bag of chips",
  "On a scale from 1 to 10, you're an 11",
  "You are strong",
  "You're even more beautiful on the inside than you are on the outside",
  "You have the courage of your convictions",
  "I'm inspired by you",
  "You're like a ray of sunshine on a really dreary day",
  "You are making a difference",
  "You bring out the best in other people",
  "Your ability to recall random factoids at just the right time is impressive",
  "You're a great listener",
  "How is it that you always look great, even in sweatpants?",
  "Everything would be better if more people were like you!",
  "I bet you sweat glitter",
  "You were cool way before hipsters were cool",
  "That color is perfect on you",
  "Hanging out with you is always a blast",
  "You always know -- and say -- exactly what I need to hear when I need to hear it",
  "You may dance like no one's watching, but everyone's watching because you're an amazing dancer!",
  "Being around you makes everything better!",
  'When you say, "I meant to do that," I totally believe you',
  "When you're not afraid to be yourself is when you're most incredible",
  "Colors seem brighter when you're around",
  "You're more fun than a ball pit filled with candy. (And seriously, what could be more fun than that?)",
  "That thing you don't like about yourself is what makes you so interesting",
  "You're wonderful",
  "You have cute elbows. For reals! ",
  "Jokes are funnier when you tell them",
  "You're better than a triple-scoop ice cream cone. With sprinkles",
  "You are really kind to people around you",
  "You're one of a kind!",
  "If you were a box of crayons, you'd be the giant name-brand one with the built-in sharpener",
  "You should be thanked more often. So thank you!!",
  "Our community is better because you're in it",
  "Someone is getting through something hard right now because you've got their back. ",
  "You have the best ideas",
  "You always find something special in the most ordinary things",
  "Everyone gets knocked down sometimes, but you always get back up and keep going",
  "You're a candle in the darkness",
  "You're a great example to others",
  "Being around you is like being on a happy little vacation",
  "You always know just what to say",
  "You're always learning new things and trying to better yourself, which is awesome",
  "If someone based an Internet meme on you, it would have impeccable grammar",
  "You could survive a Zombie apocalypse",
  "You're more fun than bubble wrap",
  "When you make a mistake, you try to fix it",
  "Who raised you? They deserve a medal for a job well done",
  "You're great at figuring stuff out",
  "Your voice is magnificent",
  "The people you love are lucky to have you in their lives",
  "You're like a breath of fresh air",
  "You make my insides jump around in the best way",
  "You're so thoughtful",
  "Your creative potential seems limitless",
  "Your name suits you to a T",
  "When you say you will do something, I trust you",
  "Somehow you make time stop and fly at the same time",
  "When you make up your mind about something, nothing stands in your way",
  "You seem to really know who you are",
  "Any team would be lucky to have you on it",
  'In high school I bet you were voted "most likely to keep being awesome."',
  "I bet you do the crossword puzzle in ink",
  "Babies and small animals probably love you",
  "If you were a scented candle they'd call it Perfectly Imperfect (and it would smell like summer)",
  "There's ordinary, and then there's you",
  "You're someone's reason to smile",
  "You're even better than a unicorn, because you're real",
  "How do you keep being so funny and making everyone laugh?",
  "You have a good head on your shoulders",
  "Has anyone ever told you that you have great posture?",
  "The way you treasure your loved ones is incredible",
  "You're really something special",
  "Thank you for being you",
  "You look great!",
  "You look awesome!",
  "You look vibrant and healthy!",
  "It looks nice on you!",
  "You look so young",
  "Your skin is glowing",
  "Your hair is so shiny",
  "You’ve worked so hard, you must be very proud of yourself!",
  "You have a great way of explaining it",
  "You demonstrate it so well",
  "It is easy to follow your instructions",
  "You are a great listener",
  "You have such a contagious laugh.",
  "You have such a happy smile",
  "You are such an inspiration",
  "You’re so talented",
  "You’re such a model for behavior",
  "You’re a great dancer",
  "Your choice of Facebook profile picture is wonderful",
  "You self-control is admirable",
  "What’s up gorgeous!",
  "You are a fountain of knowledge",
  "How do you get your hair to look like that?",
  "You make it so easy to listen to you",
  "You are a great storyteller",
  "You have such valuable life",
  "If there were a copy of you in each country around the world. The world is fascinating!",
  "You are so smart!",
  "You’re so approachable",
  "You are cool!",
  "You are so positive",
  "There is such a great feeling around you",
  "It’s perfect!",
  "You are so supportive!",
  "You have such an interesting name",
  "It’s fun to be around you.",
  "You have a warm voice",
  "What a great success!",
  "I’m so proud of you",
  "You’re so trustworthy",
  "You are a great leader!",
  "I have lots to learn from you!",
  "You can do that. You are good with things like that",
  "It is fun to hang around with you",
  "You are so photogenic",
  "You look better than your photo",
  "You are so flexible. It makes it easy to work with you",
  "Wow, it required lots of courage to do that. You are so brave!",
  "You are bubbly and happy! It is inspiring! It is contagious! It is awesome!",
  "You are so graceful",
  "You are very ethical and trustworthy",
  "People will follow you in this quest",
  "You are very honest",
  "You are very perceptive",
  "Your methods really work",
  "You are punctual, it makes it pleasure to work with you",
  "Your work has a superior quality",
  "You are sharp!",
  "You are a great problem solver",
  "You are very responsible",
  "Your resilience is remarkable",
  "You are wise",
  "You are very keen. It is a great quality!",
  "Your imagination is inspiring",
  "Your input is valuable",
  "You’re a great team player",
  "You are very clever",
  "Your idea is very clever",
  "You are strong!",
  "You are so funny",
  "You are out of this world",
  "You make a great difference",
  "Your optimism is wonderful",
  "You sound very confident about it. Go for it!",
  "You are so sweet",
  "You are ageless",
  "You are such fun",
  "You are very resourceful. It is a great quality",
  "It is so romantic",
  "You are very committed",
  "You are peaceful. It feels great to be around you",
  "You are usually right. Trust yourself!",
  "You have a free spirit",
  "You are a genius",
  "You make the world a better place just by being in it",
  "It is great to have you around",
  "You outdone yourself everyday",
  "Keep up the good work",
  "You are very special!",
  "You have it in you!",
  "You’re a good sport!",
  "You’re a great reader, books and minds",
  "You have a great collection of books",
  "You are the best!",
  "You are super!",
  "You’ve made a great progress!",
  "You rock!",
  "You are very patient",
  "You are an angel",
  "You are a life savior!",
  "Your smile lights up the room",
  "Your positive energy is palpable",
  "You inspire me",
  "You bring out the best in me",
  "You have a great sense of style",
  "You have beautiful hair",
  "You are always honest and real and I appreciate your authenticity",
  "You bring out the best in people",
  "You are a great leader",
  "I love how good you are with children",
  "Thank you for your service",
  "You are always so clean",
  "You speak so eloquently",
  "You are so goal driven",
  "Thank you for being there for me in my rough times",
  "I want to grow up to be just like you",
  "You are a great coach",
  "You are a great listener",
  "You are so motivating",
  "Thank you for being yourself around me",
  "You have the greatest laugh",
  "You are going to be great",
  "That color of clothing looks amazing on you",
  "You are so good at time management",
  "You are so kind",
  "You are always so helpful",
  "You have the whitest teeth. Or the best smile of all time!",
  "You always make my day when we hang out",
  "I love the things you don’t like about yourself",
  "You are so captivating",
  "I always tell people how amazing you are",
  "Spending time with you is my best use of time",
  "I love you just the way you are",
  "I believe in you",
  "You are so creative",
  "I think about you a lot",
  "You are so attractive",
  "I think your ethnicity is so cool and unique",
  "You are so powerful",
  "I appreciate how well you keep eye contact with people when they talk",
  "You are so artistic",
  "You have such a great vocabulary",
  "You persevere through anything and you inspire me because of it",
  "I appreciate your taste in music",
  "You have the most interesting perspectives",
  "Thank you for all the value you have brought me",
  "You have such a good work ethic. You are such a hard worker",
  "I love how much you believe in the causes you support",
  "You are so stable",
  "You are the most kind person I have ever met",
  "You have the prettiest eyes",
  "I see greatness in you",
  "You are always so committed to whatever you do",
  "You never give up",
  "You are the perfect example of the best human",
  "You are so popular!",
  "Everyone loves you!",
  "You always keep your word",
  "I want to be more like you",
  "Your a warrior!",
  "Your a champion",
  "I pray for you",
  "I see you doing great things with your life",
  "You could become president if you wanted to!",
  "You have kindness in your eyes",
  "You are the most unique person I know and have ever met",
  "You are always so optimistic at work",
  "Never stop being you",
  "I can be open and honest with you about anything",
  "There should be a big statue in the city because of how awesome you are",
  "Spending time with you is the best use of time",
  "You always give the best advice",
  "You are so incredibly selfless",
  "Mother Theresa has nothing on you!",
  "You are the definition of unconditional love",
  "I am so proud of all you accomplished",
  "You have beautiful skin!",
  "You are one in a million!",
  "I am honored to know you",
  "You are a friend but are more like family!",
  "I think about you a lot!",
  "Thank you for existing",
  "I appreciate the way you challenge me",
  "Your energy is infectious",
  "You’re my constant reminder that people can be good",
  "The world would be so boring without you",
  "Are you for real?",
  "You make the little things feel big",
  "Loving you feels like the most natural thing",
  "You impress me every single day",
  "Your capacity for kindness is boundless",
  "There’s no one like you",
  "You’re not as dumb as you let people think you are",
  "You’re beautiful",
  "Your soul is gorgeous",
  "You’re more of a superhero than any Marvel character out there",
  "Mating with you would be a smart evolutionary play",
  "Some people are radiators—they make you feel warm when you’re around them",
  "I’ve never met anyone as caring as you",
  "You have such a good heart",
  "You are truly unforgettable",
  "Wow. You",
  "You make monogamy seem easy",
  "Please never stop being you",
  "You are beautiful inside and out",
  "Your touch is so healing",
  "Your very presence is reassuring",
  "You are a life elixir",
  "Things shift when you enter the room",
  "You are light",
  "You have such a generous spirt",
  "How did you learn to be so good?",
  "Your heart must be ten times the average size",
  "It’s as if you never learned to be bitter",
  "I want to grow into a person like you",
  "I want to grow up to be just like you",
  "I’ve never met a person quite like you",
  "Your parents must be so proud",
  "There should be a monument of you",
  "You are just beyond",
  "I can’t quite fathom a world with you",
  "You are awesomeness personified",
  "There’s nothing I’d rather do than spend time with you",
  "The very thought of you makes me feel warm and fuzzy",
  "Is there a day you haven’t made better?",
  "You’re the only person I want to come back to when it feels like the rest of the world has become too much",
  "You’ve shown me how to be kinder person",
  "The way you live your life challenges me and has helped me grow",
  "You’re really good at all the things you do. And even the things you think you don’t do so well, I like how you do it anyway, without caring what anyone thinks",
  "If you died or something happened to you, I would delete your browser history for you",
  "Even if you were cloned, you'd still be one of a kind. And the better looking one",
  "I would love to spend every minute of every day with you, but some days I actually have to get stuff done",
  "Your smile is proof that the best things in life are free",
  "You're smarter than Google and Mary Poppins combined",
  "You're not someone I pretend to not see in public",
  "I don't have a favourite colour, It's pretty much whatever you are wearing",
  "You are like a corner piece of a puzzle. Without you, the world is completely lost",
  "You inspire friends, strangers, and stalkers. You are the inspiration to many",
  "I don't know if sarcasm is a skill, but you've certainly mastered it",
  "If you knew how much I think about you, I would be very embarrassed",
  "You look so good, I would certainly steal your photos, make a fake account and impress people online",
  "You're just as pretty as all the layers you hide behind",
  "Your face makes other people ugly",
  "I can't take my eyes off of you. Unless you notice me, then I'll quickly look away and act like it never happened",
  "Are you a beaver, because damn",
  "You're like the one sock that dissapears. I don't know what I did to lose you but I want you back",
  "If it was legal to marry food, I would still choose you over pizza",
  "You might be the primary reason for global warming",
  "I bet you make babies smile",
  "If there is one thing I like about you, its that I like more than one thing about you",
  "You have that kind of body that when others see it they realise they need to workout more",
  "You are more unique and wonderful than the smell of a new book",
  "The person who raised you deserves a medal for a job well done",
  "Did you have plastic surgery to become that attractive?",
  "I'm not drunk, just intoxicated by you",
  "You're the nothing when people ask me whats on my mind",
  "You are awkward, in a cute way. Like an elevator ride, but with puppies",
  "It's too bad you don't see what I see, if you did you'd smile and keep looking",
  "You know what's awesome? Chocolate cake, oh and your face",
  "Every day without you is like a day without my phone, I just don't know what to do with myself",
  "I'm really good at people-watching. I'm so glad I can share that hobby on you",
  "You make everything better. If people were more like you the world would be perfect",
  "You're not lazy, just that the people around you are way too active",
  "Actions speak louder than words, and yours tell an incredible story",
  "Any team would be lucky to have you on it",
  "As cheesy as this is, I'm telling the truth: on a scale from 1 to 10, you're an 11",
  "Being around you always makes the day better",
  "Every day, you are making a difference, even if you don't realize you are doing it",
  "Everything seems brighter when you are near",
  "For how hard you have worked in your life, you deserve an award",
  "Hanging out with you is the best and a blessing",
  "Has anyone ever told you that you have great posture?",
  "How is it that you always look great, even in sweatpants and a sweater? You slay any look you have",
  "If someone based a movie off of you, it would win an Oscar because you're that incredible",
  'If there was a superlative about you, it would be "most likely to keep being awesome."',
  "If you record an album, your voice will be heard all around the world",
  "If you were a scented candle they'd call it 'Perfectly Imperfect' (and it would smell like summer)",
  "No one is quite like you. You're one of a kind",
  "Nothing stands in your way because you are a determined person",
  "Now thinking about it, you would win an Oscar because your acting is off the charts and you would dominate on the screen",
  "Our lives would be incomplete without you in it",
  "Our world is better because you're in it",
  "Pentatonix would gladly take you into their group",
  "Remember: you are worth it",
  "Short, sweet, and to the point: You're wonderful",
  "The people you love are lucky to have you in their lives, like me",
  "There's ordinary, and then there's you",
  'To quote Liza Koshy, "You are beautiful just the way you is. Even if you are grammatically incorrect."',
  "We all get knocked down, but you say 'no' and get back up and keep going",
  "When you see a mistake, you fix it, even if you have nothing to do with it",
  "Whenever anyone is around you, your presence makes everything better!",
  "Whenever you say 'hello,' you make somebody's day",
  "Whenever you tell stories, I am captivated because you are interesting to listen to and you're great to have a conversation with",
  "Whenever your hair blows in the wind, you look like you are ready to burst out into song",
  "You always have the best ideas",
  "You always know exactly what I need to hear when I need to hear it. Thank you",
  "You always know just what to say",
  "You always listen to others. You're a good listener",
  "You always look great. Even if you're in a t-shirt and shorts or in Badin's uniform. You kill it every day",
  "You always tell the truth",
  "You are a breath of fresh air",
  "You are a fierce, brave warrior. You will fight and protect your friends until the very end",
  "You are a gift to those around you",
  "You are a great role model to others",
  "You are a light to all. You brighten up the room with your presence",
  "You are a lovely human being to have in everyone's life",
  "You are a reason to smile and be happy",
  "You are a star because you shine even in the darkest times",
  "You are a true, born leader",
  "You are a trustworthy friend",
  "You are an inspiration",
  "You are appreciated and I appreciate you",
  "You are beautiful on the outside and the inside",
  "You are enough. Just in case you didn't hear me, you are enough. :)",
  "You are perfect just the way you are. Don't forget that",
  "You are so funny and make everyone laugh!",
  "You are so polite. Like in any situation, you are so nice and polite",
  "You are so strong. Even through the roughest times, you are strong and refuse to fall",
  "You are so thoughtful about yourself and others",
  "You are the brightest treasure because people like you are hard to find",
  "You are truly special",
  "You are you and you should be proud of yourself",
  "You bring out the best in everyone that you meet",
  "You can take on any challenge and own it. You never give up",
  "You could survive a Zombie apocalypse because you're such a badass",
  "You figure things out because you're quick on your toes",
  "You have a calming aura about you, which makes everything around us slow down so that we can be relaxed",
  "You have a purpose in this world. You may not see it yet, but you have a purpose",
  "You help people whenever they need it",
  "You know who you are, which I am proud of you for",
  "You make everyone happy, wherever you go",
  "You make time stop and fly at the same time",
  "You may not realize it but someone is getting through a hard time right now because you've got their back",
  "You should be thanked more often...thank you!!",
  "You were always cool, even as a kid",
  "You work things out in a group and you make sure everyone works together and gets it done",
  "You would be a stunning model",
  "You would the rule the world if you could. I would vote for you to",
  "You're a candle in the darkness",
  "You're always learning new things and you apply it to your life which is pretty cool when you think about it",
  "You're gorgeous, even if you don't think you are. You are so gorgeous",
  "You're more fun than a ball pit filled with candy. (And seriously, what could be more fun than that?)",
  "You're not afraid to be yourself",
  "Your dance moves = amazing and lit AF",
  "Your eyes take my breath away. I'm serious, though. They're so captivating",
  "Your flame of courage is so bright that it will never go out",
  "Your jokes are so funny. Keep it up because they make people's day",
  "Your kindness is intoxicating",
  "Your laugh is contagious. Your laugh makes me want to laugh, because it makes me feel good",
  "Your sense of humor is so great. Your jokes make people laugh until they cry and their chest hurts",
  "Your singing pipes are phenomenal. Keep singing on!",
  "Your smile makes my day brighter. Whenever you smile, I want to smile",
  "Your style. Omg. You look like you could run the world",
  "I Bet You Make Babies Smile.",
  "You Have Impeccable Manners.",
  "You Are The Most Perfect You There Is.",
  "Your Perspective Is Refreshing.",
  "You Should Be Proud Of Yourself.",
  "You’re More Helpful Than You Realize.",
  "You’ve Got All The Right Moves!",
  "Your Kindness Is A Balm To All Who Encounter It.",
  "You’re Even More Beautiful On The Inside Than You Are On The Outside.",
  "When You’re Not Afraid To Be Yourself Is When You’re Most Incredible.",
  "If You Were A Box Of Crayons, You’d Be The Giant Name-Brand One With The Built-In Sharpener.",
  "You’re A Candle In The Darkness.",
  "Actions Speak Louder Than Words, And Yours Tell An Incredible Story.",
  "In High School, I Bet You Were Voted “Most Likely To Keep Being Awesome.”",
  "You’re Really Something Special.",
  "Babies And Small Animals Probably Love You.",
  "If Cartoon Bluebirds Were Real, A Couple Of ’Em Would Be Sitting On Your Shoulders Singing Right Now.",
  "You’re More Fun Than A Ball Pit Filled With Candy.",
  "You Always Know How To Find That Silver Lining.",
  "You’re More Fun Than Bubble Wrap.",
  "How Do You Keep Being So Funny And Making Everyone Laugh?",
  "You Have The Courage Of Your Convictions.",
  "You Are Making A Difference.",
  "You’re That “Nothing” When People Ask Me What I’m Thinking About.",
  "You’re A Gift To Those Around You.",
  "You Are Astoundingly Gorgeous And That’s The Least Interesting Thing About You.",
  "Your One Smile Can Make My Day.",
  "You Are So Wise.",
  "You’re Perceptive.",
  "You’re A Brilliant Listener.",
  "You Are Very Good At Seeing The Best In People, Even When Everyone Else Sees The Worst.",
  "You’re The Person Everyone Wants On Their Team.",
  "If I Threw Something At You With No Warning, I Bet You’d Catch It.",
  "You Have An Adventurous Spirit.",
  "You Embody All The Best Qualities Of Each Hogwarts House, Rolled Into One.",
  "I Always Learn So Much From You.",
  "Talking To You Is So Refreshing. I’m Happy That We Can Communicate Like This All The Time.",
  "That Is An Excellent Choice. I’m Glad You Picked That.",
  "Every Guy In This Room Has Been Staring At You.",
  "There’s Just Something About You…",
  "You Always Know When To Lend A Hand.",
  "You’re A Savvy Problem-Solver.",
  "I Love Your Enthusiasm.",
  "I Appreciate Your Trust.",
  "You’ve Got A Killer Work Ethic.",
  "Your Positive Attitude Is Infectious.",
  "I Love Your Ideas.",
  "You’re Great At Taking Initiative.",
  "Thank You For Being So Flexible.",
  "You Have A Mind For Detail.",
  "You Really Know How To Treat A Woman.",
  "You Always Know Exactly What To Say.",
  "Is There Anything You CAN’T Do?",
  "You Look Really Good In That Suit.",
  "Your Outlook On Life Is Amazing.",
  "You’re An Awesome Friend.",
  "Everything Would Be Better If More People Were Like You!",
  "You Were Cool Way Before Hipsters Were Cool.",
  "Hanging Out With You Is Always A Blast.",
  "Everyone Gets Knocked Down Sometimes, But You Always Get Back Up And Keep Going.",
  "When You Make Up Your Mind About Something, Nothing Stands In Your Way.",
  "You Seem To Really Know Who You Are.",
  "There’s Ordinary, And Then There’s You.",
  "Even If You Were Cloned, You’d Still Be One Of A Kind. And The Better-Looking One.",
  "You’re Smarter Than Google And Mary Poppins Combined.",
  "Your Face Makes Other People Ugly.",
  "If It Was Legal To Marry Food, I Would Still Choose You Over Pizza.",
  "You Are More Unique And Wonderful Than The Smell Of A New Book.",
  "You Are So Beautiful I Would Certainly Steal Your Photos, Make A Fake Account And Impress People Online.",
  "Looking Like A Complete Idiot With You Is Really Fun.",
  "I Would Hang Out With You Even If You Hadn’t Showered For A Couple Days.",
  "You’re One Of My Favorite Drunken Karaoke Partners.",
  "You Have Really Good Taste In Friends.",
  "I Would Go On An 18-Hour Road Trip With You, I Like You That Much.",
  "You Know, You’re Almost As Wonderful As Pizza. Almost.",
  "You’re Like The Human Form Of Sweatpants… Because I’m So Comfortable With You.",
  "Luckily, You’re Not A Drug, Because I Would Be A Nasty Addict And You’d Have To Pay For Rehab.",
  "Polar Bears And Penguins Should Fear Your Cuteness.",
  "Your Eyes Are So Fierce, It’s Like I’m Looking At Beyoncé Strut.",
  "You Are Not Someone I Pretend To Not See In Public.",
  "Compared To What I Would Do For You, The Legend Of Zelda Is Just Child’s Play.",
  "You inspire people.",
  "You have a way with words.",
  "You always know the right thing to say.",
  "You have a great speaking voice.",
  "Your mother raised you right.",
  "You see the best in people.",
  "You have the coolest handwriting.",
  "You’re fearless.",
  "I love your sense of style.",
  "You’re one of those people who can wear anything and look good in it.",
  "That color looks fantastic on you.",
  "You never look any older. I’m not saying you’re a vampire, but I’m not NOT saying you’re a vampire.",
  "I wish more people were like you.",
  "You’re like ice cream…you’re cool and you’re sweet.",
  "Do you ever take a day off from being fabulous?",
  "You have the patience of a saint.",
  "You’re living your best life.",
  "You’re one of the most awesome people I know. And I know a lot of awesome people!",
  "You have the best hair.",
  "You’re a badass.",
  "You don’t let anything get you down.",
  "You’re such a good photographer.",
  "Your smile lights up a room.",
  "You don’t just talk about being a Christian; you live it every day.",
  "You have good manners.",
  "You have good posture.",
  "I wish I had half your energy!",
  "You have the best taste in music.",
  "I love hearing what you’re up to—it’s always something interesting!",
  "You have charisma.",
  "When you get famous, I want to be the president of your fan club.",
  "Some of your jokes go right over people’s heads, but I think that’s why I enjoy them so much!",
  "I love your glasses.",
  "Is it easy to be so awesome, or do you have to work at it?",
  "You’re so perfect that if I didn’t like you, it would be kind of annoying.",
  "You’re so good at complimenting people!",
  "You're even more beautiful on the inside than you are on the outside.",
  "You bring out the best in other people.",
  "You are making a difference.",
  "You should be proud of yourself.",
  "You put a lot of thought into everything that you do.",
  "You are the best man out there.",
  "You are so irresistibly charming.",
  "Your style is undisputed. It's yours and only yours.",
  "Your hair looks amazing. How do you manage it so well?",
  "That color you are wearing looks really good on you.",
  "Have you been working out? Your body seems to be in perfect shape.",
  "Wow, you weren’t lying when you said you were hitting the gym!",
  "Your good looks are always a pleasure to see.",
  "You are as honest as an angel, and as handsome as a devil.",
  "You are so chivalrous, darling.",
  "You are so desirable to the world.",
  "You are gentleman among gentlemen.",
  "Your attractiveness is off the charts.",
  "People like to work with you because they trust you and your abilities.",
  "You’re amazing at everything you do.",
  "Whatever you put your mind to, you can achieve it no matter what.",
  "The world needs you. You have the power to make it better.",
  "Surviving a zombie apocalypse must be a piece of cake for you.",
  "Your impact on people's lives is immeasurable, inspiring change wherever you go.",
  "Your honesty and charm make you a rare gem in this world.",
  "The way you carry yourself in that color is simply captivating.",
  "Your hair is always on point – seriously, what's your secret?",
  "Your commitment to working out is paying off in remarkable ways.",
  "You possess an unmatched charisma that draws people in effortlessly.",
  "Your thoughtfulness and consideration for others are truly admirable.",
  "Your dedication to fitness is evident, and your physique is impressive.",
  "Your appearance never fails to catch attention in the best way possible.",
  "Your kindness radiates from within, lighting up any room you enter.",
  "Your talent and skill seem boundless – you excel in everything you pursue.",
  "Your ability to collaborate and lead makes you a valuable asset to any team.",
  "Your allure and magnetism are hard to resist; you leave a lasting impression.",
  "Your personal style is distinctive and a true reflection of your individuality.",
  "You have beautiful eyes.",
  "Truth be told, you could be a fashion model.",
  "Are you sure you have never modeled before?",
  "Everything about you is sexy.",
  "You are cuter than any celebrity out there.",
  "You’re amazing at everything you do.",
  "You're the Queen!, Queen of your world",
  "You’ve got a sexy personality.",
  "You look beautiful even when you don’t try.",
  "You’re even sexy when you’re bossy.",
  "You have the sweetest heart.",
  "No matter what you encounter, you are always classy.",
  "You’re like sunshine when it’s raining.",
  "Red looks perfect on you, like it’s made for you.",
  "That is such a great choice. It was waiting to be yours",
  "Angels didn't exist until you landed",
  "Whoever is lucky enough to end up with you will never be bored a day in their life.",
  "They say that there are plenty of fish in the sea, but you are the perfect catch.",
  "Thank you for setting a great example,",
  "You come up with fantastic ideas!",
  "You're a savvy problem-solver.",
  "You are such an incredible problem solver.",
  "If cartoon bluebirds were real, a couple of 'em would be sitting on your shoulders singing right now.",
  "You bring out the best in other people.",
  "Bet you sweat glitter.",
  "You're a great example to others.",
  "Someone is getting through something hard right now because you've got their back. Nice work.",
  "Your hair always looks fabulous – what's your secret?",
  "Your grace and kindness are emblematic of a true modern lady.",
  "You radiate a natural charm that draws people in effortlessly.",
  "Your honesty and charisma make you a rare gem in this world.",
  "Your beauty is matched only by your inner kindness and integrity.",
  "Your confidence and poise set you apart as a role model for others.",
  "Your talents and skills are awe-inspiring – you excel in every endeavor.",
  "You light up rooms with your warmth, making everyone valued.",
  "Your positivity is contagious, uplifting even the gloomiest.",
  "Your influence inspires change; your impact is remarkable.",
  "Your accomplishments reflect dedication and boundless potential.",
  "Your compassion warms hearts; a truly caring soul.",
  "You radiate charm, drawing people in effortlessly.",
  "Style mirrors your uniqueness; a beautiful reflection.",
  "Your positive impact is significant; you make a difference.",
];

export default localQuotes;
